-- TimeJournal categories seeded from TimeJournal-2026.xlsx (13 top-level, 65 sub).
-- Subcategories inherit their parent's colour (colour-group model).
with me as (select id as uid from users where email = 'abhishek.projects86@gmail.com'),
ins_top as (
  insert into categories (user_id, parent_id, code, name, color, sort_order, description)
  select (select uid from me), null, t.code, t.name, t.color, t.ord, t.descr
  from (values
    ('A','Sleep','#8b5cf6',1,null),
    ('B','Hanging out','#f59e0b',5,'Unnecessary wasted time with family due to various reasons'),
    ('C','Friends','#ec4899',9,null),
    ('D','Inactivity','#64748b',14,'Staring at a ceiling or wall and being in my thoughts. Usually when not being able to sleep or sitting in waiting rooms.'),
    ('E','Eating','#f97316',15,null),
    ('F','Occupation','#3b82f6',21,'I am a BSc student for land surveying and land management engineering.'),
    ('G','Computer','#06b6d4',32,null),
    ('H','Travel','#14b8a6',40,null),
    ('I','Commute','#22c55e',49,'Travel specifically between home and place of occupation.'),
    ('J','Gaming','#d946ef',53,'can rename this segment to recreation? -can add drawing, music, gaming here'),
    ('K','Maintenance','#84cc16',60,null),
    ('L','Going out','#f43f5e',65,'Leaving the house for various reasons.'),
    ('M','Media consumption','#a855f7',71,null)
  ) as t(code,name,color,ord,descr)
  returning id, code, color
)
insert into categories (user_id, parent_id, code, name, color, sort_order, description)
select (select uid from me), p.id, s.code, s.name, p.color, s.ord, s.descr
from (values
    ('Aa','Nap','A',2,'I don''t take naps - I sleep - so If I ever log this, it means I didn''t take the nap, the nap took me'),
    ('Ab','Insomnia','A',3,null),
    ('Ac','Sleep Hangover','A',4,null),
    ('Ba','with Family','B',6,'Genuine good times, necessary ones'),
    ('Bb','Family Call','B',7,null),
    ('Bc','Online chatting','B',8,null),
    ('Ca','Necessary','C',10,'When you get dragged into something you don''t want to but have to'),
    ('Cb','Unnecessary','C',11,'When you get dragged into something you don''t want to'),
    ('Cc','Inner Circle','C',12,'The bois'),
    ('Cd','Wasted Time','C',13,'Wasted time in hanging out when you are ready but need to wait or other practical problems that waste time in social settings'),
    ('Ea','Breakfast','E',16,'Usually missed, except a few lucky days.'),
    ('Eb','Lunch','E',17,'The first of the two major meals of a given day, regardless of when in the day it occurs.'),
    ('Ec','Dinner','E',18,'The second of the two major meals.'),
    ('Ed','Other','E',19,null),
    ('Ee','Cooking','E',20,'Whenever I am in the kitchen making anything - cooking, baking, brewing'),
    ('Fa','Online Learning','F',22,'Learning stuff online - usually lectures from YouTube.'),
    ('Fá','Offline learning','F',23,'Learning from books, peers or anything that is primarily offline'),
    ('Fb','Studying','F',24,'Any effort done for school outside of classes.'),
    ('Fc','Peripherals','F',25,'applying for internships, updating resume'),
    ('Fd','Idling','F',26,'Figuring out what or how to do for something productive'),
    ('Fe','Internship','F',27,'Gotta intern somewhere to get the degree.'),
    ('Ff','Projects','F',28,'Projects done to learn stuff, usually coding'),
    ('Fg','Discussions','F',29,'Time spent in doing discussions for work. Not working but doing stuff related to work - meetings, chats, scrums'),
    ('Fh','Housework','F',30,'Washing utensils, clothes. Arranging Desk etc - Tasks done to assist routine functioning of life.'),
    ('Fi','Gardening','F',31,null),
    ('Ga','Personal projects','G',33,'Projects for personal fulfilment'),
    ('Gb','Reddit','G',34,null),
    ('Gd','Research','G',35,'Surfing the web, gathering knowledge about random stuff for future use.'),
    ('Ge','Idling','G',36,'When I''m just making rounds looking at things without interacting with them much, for the purpose of figuring out what to do next.'),
    ('Gf','Instagram','G',37,null),
    ('Gg','Twitter','G',38,null),
    ('Gh','Other','G',39,null),
    ('Ha','Car','H',41,'Someone else is driving.'),
    ('Há','Car driving','H',42,'I''m driving.'),
    ('Hb','Bus','H',43,null),
    ('Hc','Metro','H',44,null),
    ('Hd','Train','H',45,null),
    ('He','Walk','H',46,null),
    ('Hé','Hike','H',47,'Walking not to get somewhere but to be somewhere. Includes sightseeing and nature hikes.'),
    ('Hf','Airplane','H',48,null),
    ('Ia','Car','I',50,null),
    ('Ib','Bus','I',51,null),
    ('Ic','Walk','I',52,null),
    ('Ja','Board game','J',54,null),
    ('Já','Game preparation','J',55,'Reading board game rulebooks, explaining rules, as well as putting it back in the box afterwards.'),
    ('Jb','Video game','J',56,null),
    ('Jc','with Cats','J',57,null),
    ('Jd','with Kids','J',58,'Playing with the toddler in the family mostly.'),
    ('Je','Other','J',59,null),
    ('Ka','in Bathroom','K',61,'Hygiene routine things like shaving or combing.'),
    ('Ká','Bathing','K',62,null),
    ('Kb','Exercising','K',63,null),
    ('Kc','Other','K',64,null),
    ('La','Grocery shopping','L',66,null),
    ('Lb','Restaurant','L',67,'Going out to eat - be it restaurants, cafes or roadside stalls.'),
    ('Lc','Trips','L',68,'Going out to a place for recreational purposes'),
    ('Ld','Administration','L',69,'Going out to deal with work- doctor, bank, medicines etc'),
    ('Le','Other','L',70,null),
    ('Ma','Videos','M',72,'Specifically content videos only, mostly YouTube. For example watching a movie on YT is logged as Mc.'),
    ('Mb','TV shows','M',73,null),
    ('Mc','Movies','M',74,null),
    ('Md','Articles','M',75,'Newspapers, magazines, online articles, any product of journalism, as well as Wikipedia articles.'),
    ('Me','Book','M',76,null),
    ('Mf','Porn','M',77,null),
    ('Mg','Anime','M',78,null)
) as s(code,name,parent,ord,descr)
join ins_top p on p.code = s.parent;
